version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    insecure-external-code-execution: allow
    schedule:
      interval: "monthly"
    labels:
      - "maintenance"
      - "dependencies"
    groups:
      trame:
        patterns:
          - "trame"
          - "trame-*"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    groups:
      artifacts:
        patterns:
          - "actions/upload-artifact"
          - "actions/download-artifact"
    labels:
      - "maintenance"
      - "dependencies"
