repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.2
    hooks:
      - id: mypy
        # File list is specified via [tool.mypy].files in pyproject.toml,
        # so pre-commit should not pass filenames or mypy will see duplicates.
        # See: https://github.com/python/mypy/issues/4008#issuecomment-708060733
        pass_filenames: false

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args: ["docs examples examples_flask pyvista tests", "*.py *.rst *.md"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: no-commit-to-branch
        args: [--branch, main]

  # this validates our github workflow files
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.1
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.3
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]
      - id: ruff-format
