name: pyvistaqt-env
channels:
  - conda-forge
dependencies:
  - python>=3.5
  - numpy
  - vtk
  - scooby>=0.5.1
  - meshio>=4.0.3, <5.0
  - matplotlib
  - appdirs
  - pyqt>=5.11
  - qtpy
  - imageio>=2.5.0
  - imageio-ffmpeg
  - colorcet
  - cmocean
  - itkwidgets>=0.25.2
  - tqdm
  - pytest
  - pytest-cov
  - pytest-qt
  - pyvista
  - codecov
  - hypothesis>=5.8.0
  - pip
  - pip:
      - pytest-memprof
