name: pyvistaqt-env
channels:
  - conda-forge
dependencies:
  - python>=3.5,<3.9
  - codecov
  - ipython
  - numpy
  - pytest
  - pytest-cov
  - pytest-qt
  - qtpy
  - scooby>=0.5.1
  - pip
  - pip:
      - vtk
      - pyvista
      - pytest-memprof
