name: pyvistaqt-env
channels:
  - conda-forge
dependencies:
  - python
  - codecov
  - ipython
  - mypy
  - numpy
  - pytest
  - pytest-cov
  - pytest-qt
  - qtpy>=1.9.0
  - scooby>=0.5.1
  - toml
  - pip
  - vtk
  - pyvista
  - pip:
      - pytest-memprof
      - sphinx-gallery
