[tool.black]
line-length = 88
skip-string-normalization = true
target-version = ["py39"]
exclude='\.eggs|\.git|\.mypy_cache|\.tox|\.venv|_build|buck-out|build|dist|node_modules|rwi\.py'
check = true

[tool.pydocstyle]
match = '(?!(coverage|test_|rwi)).*[.]py'