name: autofix.ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 1 * * 1" # At 01:00 every Monday
  workflow_dispatch:

permissions:
  contents: write

jobs:
  autofix:
    name: "prek pre-commit"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v7
      - name: Do a deeper checkout
        if: github.event_name != 'pull_request'
        run: |
          set -x
          git fetch origin "${{ github.event.ref }}"
          git reset --hard "${{ github.event.ref }}"
      - uses: j178/prek-action@v2
        with:
          install-only: true
      - run: prek run --show-diff-on-failure --color=always --all-files
        if: github.event_name == 'pull_request'
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
        with:
          commit-message: "pyvista[bot]: prek run autofix"
        if: github.event_name == 'pull_request' && failure()
      - name: Create PR
        if: github.event_name != 'pull_request'
        run: |
          prek auto-update
          git diff && git status --porcelain
          if [[ ! $(git status --porcelain) ]]; then
            echo "No changes to commit"
            exit 0
          fi
          set -xeo pipefail
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          BRANCH=prek/$(date '+%Y%m%d')
          git checkout -b $BRANCH
          git commit -am "pyvista[bot]: Update prek"
          git push origin $BRANCH
          PR_NUM=$(gh pr create --base main --head $BRANCH --title "Update prek" --body "Created by [GitHub action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).")
          echo "Opened https://github.com/${{ github.repository }}/pull/${PR_NUM}" >> $GITHUB_STEP_SUMMARY
