name: Documentation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            **/requirements_docs.txt
      - uses: pyvista/setup-headless-display-action@main
        with:
          qt: true
      - run: pip install . -r requirements_docs.txt "PySide6!=6.5.1,!=6.7.0"
      - run: make -C docs doctest html
      - uses: peaceiris/actions-gh-pages@v4
        # Not a PR:
        if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads')
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: pyvista/pyvistaqt-docs
          publish_branch: master
          publish_dir: ./docs/_build/html
          cname: qtdocs.pyvista.org
