name: PR update
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - "main"
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically update PR
        uses: adRise/update-pr-branch@v0.10.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "main"
          required_approval_count: 1
          require_passed_checks: false
          sort: "created"
          direction: "desc"
          require_auto_merge_enabled: true
