name: PR update
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - "main"
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    # Only run on the main repository, not on forks
    if: github.repository == 'pyvista/pyvistaqt'
    steps:
      - name: Automatically update PR
        uses: adRise/update-pr-branch@v0.10.1
        with:
          # Using a PAT (Personal Access Token) instead of GITHUB_TOKEN
          # GITHUB_TOKEN doesn't have permission to update PRs from forks
          # You need to create a PAT and add it as a secret named 'PR_UPDATE_TOKEN'
          token: ${{ secrets.PR_UPDATE_TOKEN || secrets.GITHUB_TOKEN }}
          base: "main"
          required_approval_count: 1
          require_passed_checks: false
          sort: "created"
          direction: "desc"
          require_auto_merge_enabled: true
          # Only process PRs with ongoing checks if needed
          allow_ongoing_checks: false
